# Generated by Django 4.2.3 on 2023-07-07 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=10)),
                ('condition', models.TextField(max_length=300)),
                ('bought_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
